// Generated by HelpNDoc - http://www.helpndoc.com

unit Help;

interface

const
  HELP_Image2XMLUsersManual = 16;
  HELP_QuickStart = 5;
  HELP_Step1ImageProcessing = 17;
  HELP_CreatingaTemplate = 13;
  HELP_SettingupaJob = 14;
  HELP_StartingTheScanTrayUtility = 15;
  HELP_Image2XML = 6;
  HELP_IntroductiontoImage2XML = 0;
  HELP_AboutImage2XML = 1;
  HELP_MainFeatures = 2;
  HELP_FeatureList = 3;
  HELP_RoadMap = 4;
  HELP_I2XScanTray = 7;
  HELP_Introduction = 8;
  HELP_AboutI2XScanTray = 9;
  HELP_MainFeatures2 = 10;
  HELP_FeatureList2 = 11;
  HELP_RoadMap2 = 12;

implementation

end.